# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11caaf741fed4694624051e3b20fccce1600e8e75333041736ed03d078b01f596d10876a4e80ec09ccfaa2c9386487706701f2874ec49f89bc4ddac1bf18408e

test:
  secret_key_base: 0466c6f7e152ec4a5209f7a2c8104de168d8b4c92aa66f0916c2ad3df9c8890ed43f1c9bbcab055bb3007553f1a1f2fef6188eabeceeb50396f5b6a0ab233bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
